name: ThoughtCapture
options:
  bundleIdPrefix: com.thoughtcapture
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

targets:
  ThoughtCapture:
    type: application
    platform: iOS
    sources:
      - ThoughtCapture
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        PRODUCT_BUNDLE_IDENTIFIER: com.thoughtcapture.app
        PRODUCT_NAME: ThoughtCapture
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
